### ISSUE TITLE
Taxonomy TTL files empty after SSU/LSU fix

### ISSUE THREAD

**Issue by cymon** [emo-bon/analysis-results-uplifting-docker#37]
The new fix for the SSU/LSU taxonomy files results in empty (0 bytes) TTL files.

The new work.yml looks like this:

```
  - source: 
      path: ./results/taxonomy-summary/LSU/DBB.merged_LSU.fasta.mseq.tsv
      mime: text/csv
      delimiter: "\t"
      comment: "#"
      header: "OTU_ID\tLSU_rRNA\ttaxonomy\ttaxid"
    sink: ./results/taxonomy-summary/LSU/LSU-taxonomy-summary.ttl
    template_name: taxon-info-LSU.ldt.ttl
  - source: 
      path: ./results/taxonomy-summary/SSU/DBB.merged_SSU.fasta.mseq.tsv
      mime: text/csv
      delimiter: "\t"
      comment: "#"
      header: "OTU_ID\tSSU_rRNA\ttaxonomy\ttaxid"
    sink: ./results/taxonomy-summary/SSU/SSU-taxonomy-summary.ttl
    template_name: taxon-info-SSU.ldt.ttl
```

The container executes without error, produces the correct functional-annotation.ttl file, but both LSU and SSU ttl files are created but empty.

You can test this yourself:
```
git clone git@github.com:emo-bon/metagoflow-data-products-ro-crate.git
git checkout arup-testing
cd utils && ./install_arup_container.sh && cd ..
utils/arup_archive.py -d
ls -al tests/arup/data/HVWGWDSX5.UDI134/results/taxonomy-summary/SSU/
total 72
drwxr-xr-x. 2 cymon cymon  4096 May  8 12:50 .
drwxr-xr-x. 4 cymon cymon  4096 Apr 16 16:44 ..
-rw-r--r--. 1 cymon cymon 64967 Apr 16 16:44 DBB.merged_SSU.fasta.mseq.tsv
-rw-r--r--. 1 cymon cymon     0 May  8 12:50 SSU-taxonomy-summary.ttl
```

**Comment by mpo-vliz** [comment]
header changed in the work-yml, the SU-rRNA in both cases should be used, the su-indicator is injected through the template

see https://github.com/emo-bon/analysis-results-uplifting-docker/blob/a480726c84cdcc9990f4bbc8b13bf3344efe6518/work.yml#L58-L71

**Comment by cymon** [comment]
OK, just for future reference: the source data files are TSV not CSV... the following work.yml stanza work:
```
  - source:
      path: ./results/taxonomy-summary/LSU/{PREFIX}.merged_LSU.fasta.mseq.tsv
      mime: text/csv
      delimiter: "\t"
      header: "OTU_ID\tSU_rRNA\ttaxonomy\ttaxid"
      comment: "#"
    sink: ./results/taxonomy-summary/LSU/LSU-taxonomy-summary.ttl
    template_name: taxon-info-LSU.ldt.ttl
  - source:
      path: ./results/taxonomy-summary/SSU/{PREFIX}.merged_SSU.fasta.mseq.tsv
      mime: text/csv
      delimiter: "\t"
      header: "OTU_ID\tSU_rRNA\ttaxonomy\ttaxid"
      comment: "#"
    sink: ./results/taxonomy-summary/SSU/SSU-taxonomy-summary.ttl
    template_name: taxon-info-SSU.ldt.ttl
```
